name: Dart
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: Regis Cridlig <email@example.com>

environment:
  sdk: '^3.2.0'

dependencies:
  path: ^1.4.1
  js: ^0.6.1
  intl: ^0.19.0
  
dev_dependencies:
 # test: ^0.12.0
